//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom06_QuanLyBanSah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG_VOUCHER
    {
        public int MaDonHang { get; set; }
        public int MaVoucher { get; set; }
        public Nullable<decimal> SoTienGiam { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual VOUCHER VOUCHER { get; set; }
    }
}
