//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom06_QuanLyBanSah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOANTRA
    {
        public int MaHoanTra { get; set; }
        public Nullable<int> MaDonHang { get; set; }
        public string LyDo { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayYeuCau { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
    }
}
