//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom06_QuanLyBanSah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        public int UserID { get; set; }
        public string HangThanhVien { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
