//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom06_QuanLyBanSah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOUCHER()
        {
            this.DONHANG_VOUCHER = new HashSet<DONHANG_VOUCHER>();
        }
    
        public int MaVoucher { get; set; }
        public string CodeVoucher { get; set; }
        public Nullable<decimal> GiaTriGiam { get; set; }
        public string KieuGiam { get; set; }
        public Nullable<decimal> DieuKienToiThieu { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string LoaiVoucher { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG_VOUCHER> DONHANG_VOUCHER { get; set; }
    }
}
